import type { Market } from "@hyper-trader/hyperliquid/public";

export const NATIVE_DUPLICATE = {
  family: "perp",
  canonicalId: "perp:0:4",
  displaySymbol: "DUP",
  coin: "DUP",
  universeIndex: 4,
  orderAssetId: 4,
  lifecycle: "active",
  orderAvailability: "enabled",
  validationReasons: [],
  dexIndex: 0,
  dexName: "",
  dexFullName: null,
  sizeDecimals: 2,
  pricePrecision: { maxSignificantFigures: 5, maxDecimalPlaces: 4 },
  maxLeverage: 20,
  onlyIsolated: false,
  marginMode: null,
  marginTableId: null,
  dayNtlVlm: "100",
  funding: "0.0001",
  openInterest: "40",
  markPx: "10",
  prevDayPx: "8",
} satisfies Market;

export const HIP3_DUPLICATE = {
  ...NATIVE_DUPLICATE,
  canonicalId: "perp:3:9",
  coin: "omega:DUP",
  universeIndex: 9,
  orderAssetId: 130_009,
  dexIndex: 3,
  dexName: "omega",
  dexFullName: "Omega Markets",
  dayNtlVlm: "250",
  funding: "0.0003",
  openInterest: "80",
  markPx: "12",
  prevDayPx: "10",
} satisfies Market;

export const SPOT_DUPLICATE = {
  family: "spot",
  canonicalId: "spot:7",
  displaySymbol: "DUP",
  coin: "@7",
  universeIndex: 7,
  orderAssetId: 10_007,
  lifecycle: "active",
  orderAvailability: "enabled",
  validationReasons: [],
  dexIndex: null,
  dexName: null,
  sizeDecimals: 2,
  pricePrecision: { maxSignificantFigures: 5, maxDecimalPlaces: 6 },
  baseToken: {
    index: 42,
    tokenId: "0xdup",
    name: "DUP",
    fullName: "Duplicate Token",
    sizeDecimals: 2,
    weiDecimals: 8,
    isCanonical: false,
    evmContract: null,
  },
  quoteToken: {
    index: 0,
    tokenId: "0xusdc",
    name: "USDC",
    fullName: "USD Coin",
    sizeDecimals: 8,
    weiDecimals: 8,
    isCanonical: true,
    evmContract: null,
  },
  isCanonical: false,
  dayNtlVlm: "150",
  markPx: "2",
  prevDayPx: "2.5",
} satisfies Market;

export const OUTCOME_MARKET = {
  family: "outcome",
  canonicalId: "outcome:12:0",
  displaySymbol: "Higher",
  coin: "#120",
  universeIndex: 120,
  orderAssetId: 100_000_120,
  lifecycle: "active",
  orderAvailability: "browse_only",
  validationReasons: ["precision_not_provided_by_outcome_metadata"],
  dexIndex: null,
  dexName: null,
  outcome: 12,
  outcomeName: "BTC 120k",
  description: "BTC closes above 120k",
  side: 0,
  sideName: "Higher",
  encoding: 120,
  sizeDecimals: null,
  pricePrecision: null,
} satisfies Market;

export const MARKET_FIXTURE: readonly Market[] = [
  NATIVE_DUPLICATE,
  HIP3_DUPLICATE,
  SPOT_DUPLICATE,
  OUTCOME_MARKET,
];
